### ISSUE TITLE
Package.swift file

### ISSUE THREAD

**Issue by joshkopecek** [PostHog/posthog-ios#1]
It would be great to have a Package.swift file for PostHog, so it could be easily installed.

**Comment by mariusandra** [comment]
Hi, is it also allowed to add Package.swift files to purely objective-c codebases? I don't have any experience with this, however I'd be more than happy to accept a PR that adds this file!

**Comment by joshkopecek** [comment]
I tried adding the Package.swift file, but there are some issues. It doesn't like the mixed swift/objc in the Tests, and I can't seem to add the UIKit framework as a dependency in objc.

I created a fork here: https://github.com/joshkopecek/posthog-ios/tree/features/spm

**Comment by mariusandra** [comment]
Hi @joshkopecek , just checking in, did you get `posthog-ios` working with a Package.swift file in the end... or how are you currently integrating it into your app? We'd love to make setup really easy for all iOS developers. We should probably update [the docs](https://posthog.com/docs/integrations/ios-integration) to guide swift users better with the current way of installing it...

**Comment by joshkopecek** [comment]
Currently using Cocoapods to install, although Package.swift would be preferred. I did some rudimentary work on it, and looked like it would be possible, but I ran out of time. It's in my repo as mentioned above.

As I mentioned above I was struggling to get it to see the core iOS UIKit framework. It might be good to remove that anyway.

**Comment by dannyhertz** [comment]
Any progress on this? Had a call with the team today and SPM support would really make integration simpler for us.

**Comment by mariusandra** [comment]
I'd love it if someone with enough experience with ObjC/Swift dependencies could pick this up!

**Comment by mariusandra** [comment]
PR #10 and version `1.2.2` could have fixed this.
