### ISSUE TITLE
Batch HTTP 400

### ISSUE THREAD

**Issue by bddq** [PostHog/posthog-ios#103]
### Version

3.1.0

### Steps to Reproduce

Trigger any event. 
Wait for send to the `/batch` endpoint.

### Expected Result

Expected HTTP 2xx code after send.
Expected to see some events in Activity feed.

### Actual Result

No logs are shown in the Xcode console.
No events are shown in Activity feed on website.

Debug with breakpoint indicates a response status code is always `400` (`PostHogApi.batch()`) without any error.

SDK is initialised with:

```
let configuration = PostHogConfig(apiKey: postHogKey, host: "https://eu.posthog.com")

configuration.captureApplicationLifecycleEvents = false
configuration.captureScreenViews = false
configuration.debug = true

PostHogSDK.shared.setup(configuration)
```

**Comment by marandaneto** [comment]
@bddq I just checked it and it's working alright for me.
Usually, a wrong apiKey returns 401, but not 400.

What do you see in the logs if enabling `configuration.debug = true`?

**Comment by bddq** [comment]
@marandaneto As mentioned, logs are not displayed at all in Xcode console.
I'm using Xcode 14.2.

I checked the API key used. I use the right one.
I'm still having an HTTP 400 error.

I upgraded to 3.1.1, same issue.

<img width="968" alt="Capture 2024-02-08 at 17 01 12" src="https://github.com/PostHog/posthog-ios/assets/342063/48f29238-6a8e-4047-b0a5-49ad85b5fb70">

**Comment by marandaneto** [comment]
@bddq we had some DNS issues yesterday, not sure if its the same thing but I will double check.
https://status.posthog.com/incidents/qqslrk8p86hx

I will check why there are no logs as well.

**Comment by bddq** [comment]
@marandaneto I got same behaviour with default host.

BTW, I tested the same source code on another device and it works.
Device with PostHog working: iPhone 11 Pro, iOS 15.6, WiFi.
Device with PostHog *not* working: iPhone SE (3rd gen), iOS 16.2, WiFi.

Both tests were done with PostHog SDK v3.1.1.

Can it be an issue with Gzip on iOS 16 or something else making the request bad?

**Comment by marandaneto** [comment]
@bddq https://github.com/PostHog/posthog-ios/pull/104
After this PR we'd have better logging, not sure, `gzip` is wrapped in a try-catch, so it'd throw and return early instead of calling the API and returning 400.
Let me get this merged, so you can test and check the logs.

I'll try to create an emulator using iPhone SE (3rd gen), iOS 16.2, WiFi

**Comment by marandaneto** [comment]
https://github.com/PostHog/posthog-ios/releases/tag/3.1.2
If you're using GH directly, please test it, if you're using Cocoapods, it'll take a few minutes.

**Comment by bddq** [comment]
I got it. Logs are now popping in Xcode console with 3.1.2 version.

You have an issue with the `send_at` value.
The `toISO8601String(_)` currently returns `"2024-02-09T10:32:21.671 AMZ"` value for my device.
This value seems not to be supported by your server.

Why in your DateUtils you are not using an `ISO8601DateFormatter`?

**Comment by bddq** [comment]
@marandaneto my device have 12-hour time format, so the date formatter is adding ` AM` before `Z`. That's why.
I definitely advise you to use the `ISO8601DateFormatter ` if it fits your need.

**Comment by marandaneto** [comment]
oh damn, let me check this @bddq thanks!

**Comment by marandaneto** [comment]
Thanks @bddq for debugging with me.
https://github.com/PostHog/posthog-ios/releases/tag/3.1.3
