### ISSUE TITLE
Describing use of required reason API

### ISSUE THREAD

**Issue by hsingh-texada** [PostHog/posthog-ios#109]
### Problem Statement

Starting spring of 2024, Apple will be mandating the use of `xcprivacy` file to be included by all the libraries. 
The relevant Apple requirement/documentation is as follows:
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

Can you please provide timelines on when this would be resolved, as it will directly impact our AppStore submissions.

**Comment by marandaneto** [comment]
We do use the https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files says:

> You only need to supply NSPrivacyAccessedAPITypes for apps and third-party SDKs on iOS, iPadOS, tvOS, visionOS, and watchOS.

In this case, we just need to set the `CA92.1`.
