### ISSUE TITLE
Support for Swift Package Manager?

### ISSUE THREAD

**Issue by AugustDev** [PostHog/posthog-ios#12]
Currently there is no information about PostHog using SPM?

Are there plans updating project for adding this functionality?

**Comment by mariusandra** [comment]
We should support this (see the [Package.swift file](https://github.com/PostHog/posthog-ios/blob/master/Package.swift) and this PR: https://github.com/PostHog/posthog-ios/pull/10). Unfortunately we don't have anyone with a lot of experience in iOS development, so we might be missing something.

Please feel free to open a pull request or an issue with exact steps that we still need to do to add this support. :)

**Comment by jamesefhawkins** [comment]
I'd add that we're about to start hiring for a mobile developer too :)

**Comment by AugustDev** [comment]
> We should support this (see the [Package.swift file](https://github.com/PostHog/posthog-ios/blob/master/Package.swift) and this PR: #10). Unfortunately we don't have anyone with a lot of experience in iOS development, so we might be missing something.
> 
> Please feel free to open a pull request or an issue with exact steps that we still need to do to add this support. :)

I will open new issue with detail explanation of the problem I am running into. Thank you!

**Comment by JMCPH** [comment]
This is fixed in the 1.4 version and can be closed. @jamesefhawkins @mariusandra
