### ISSUE TITLE
Error importing with SPM

### ISSUE THREAD

**Issue by AugustDev** [PostHog/posthog-ios#13]
When importing `PostHog` via Swift Package Manager I end up with an error. 

`Could not build Objective-C module 'PostHog'`

![image](https://user-images.githubusercontent.com/5672094/112340649-a67ccd00-8cb8-11eb-8b3a-8cd32f22695b.png)

### To reproduce the problem:
Simply create a new Xcode project using Swift and import PostHog from "https://github.com/PostHog/posthog-ios".

I'm not sure if I'm missing something basic or the package is not compatible with SPM. All ideas are appreciated!

**Comment by arunrdd** [comment]
More specifically, XCode complains with the following error:
```
'PHGMiddleware.h' file not found
```
Occurs in the file `posthog-ios/PostHog/Classes/Payloads/PHGPayloadManager.h` on `line #2`

**Comment by JMCPH** [comment]
I'm also experiencing this problem. Did you manage to find a solution to the issue?

**Comment by JMCPH** [comment]
@arunrdd did you find a way to solve this error?

**Comment by kconrad-cls** [comment]
+1 to the people experiencing this problem.

**Comment by JMCPH** [comment]
@mariusandra what is the status on this? We are still getting this error with importing objective-c headers

**Comment by mariusandra** [comment]
Version 1.4.0 should finally fix this!
