### ISSUE TITLE
MAJOR - Deleting Application Support Directory!

### ISSUE THREAD

**Issue by nitrag** [PostHog/posthog-ios#130]
### Version

3.2.4

### Steps to Reproduce

1. Call `PostHogSDK.shared.reset()`

### Expected Result

Only delete PostHog related data

### Actual Result

PostHog wipes the entire directory!! Shame on you guys for doing this, we have valuable data in this directory. 

https://github.com/PostHog/posthog-ios/blob/a12c3418f0f38511b8dc3d8cfb572681785ecf62/PostHog/PostHogStorage.swift#L17-L20

**Comment by marandaneto** [comment]
Hi @nitrag let me check this for you.

**Comment by marandaneto** [comment]
@nitrag I can confirm the bug, so sorry about that, we'll make sure this won't happen again.
we'll cut a patch https://github.com/PostHog/posthog-ios/pull/132
just need to add some tests and make sure that there's no side effect, thanks for opening this.

**Comment by marandaneto** [comment]
Fixed by https://github.com/PostHog/posthog-ios/releases/tag/3.2.5

**Comment by nitrag** [comment]
Thank you for your quick attention to this!
