### ISSUE TITLE
warning: no rule to process file 'macos/Pods/PostHog/PostHog/Resources/PrivacyInfo.xcprivacy' of type 'text.xml' for architecture 'arm64' (in target 'PostHog' from project 'Pods')

### ISSUE THREAD

**Issue by stephane-archer** [PostHog/posthog-ios#137]
### Bug Description

```
$ flutter build macos
warning: no rule to process file 'macos/Pods/PostHog/PostHog/Resources/PrivacyInfo.xcprivacy' of type 'text.xml' for architecture 'arm64' (in target 'PostHog' from project 'Pods')
```
```
  posthog_flutter: ^4.0.0
```
```
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.5 23F79 darwin-x64, locale en-GB)
    • Flutter version 3.22.0 on channel stable at /Users/fractale/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (11 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/fractale/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 124.0.6367.208

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

**Comment by marandaneto** [comment]
I also get this warning when running https://github.com/PostHog/posthog-ios/tree/main/PostHogExampleWithPods
 
<img width="904" alt="Screenshot 2024-05-21 at 15 13 03" src="https://github.com/PostHog/posthog-ios/assets/5731772/140a0218-679a-47db-8c3f-788091d05b77">

But if I generate a privacy report:

<img width="1454" alt="Screenshot 2024-05-21 at 15 13 33" src="https://github.com/PostHog/posthog-ios/assets/5731772/f0e6ecdb-c970-46a4-ba6b-a16fcaf66201">

Everything is working correctly, it might be something with Pods or Xcode, but I don't see any difference between our setup and other libs.

**Comment by marandaneto** [comment]
Hopefully https://github.com/PostHog/posthog-ios/releases/tag/3.4.0 fixes it

**Comment by stephane-archer** [comment]
@marandaneto Is it already available for users? can you tell me what version it is so I can test?

**Comment by marandaneto** [comment]
@stephane-archer 3.4.0 as linked above, if using flutter, you just have to upgrade your pods because the flutter dep always use the latest version 3.x.x

**Comment by stephane-archer** [comment]
Pods version `- PostHog (3.2.5)`
I can still see this warning, please @marandaneto re-open this issue

**Comment by marandaneto** [comment]
Please test it using 3.4.0 as requested.

**Comment by stephane-archer** [comment]
if I delete `macos/Pods/` and `macos/Podfile.lock` this doesn't put PostHog (3.4.0), is there any commands for that?
`  posthog_flutter: ^4.0.0`

**Comment by stephane-archer** [comment]
@marandaneto I was able to update the pods and I don't see the warning anymore.
I'm confused about the fact that Pods and Flutter packages are independent, one does not force the other.
Could you clarify why PostHog is not just a Flutter package and why it needs a Pod? I'm a bit confused about how packages and Pods are related and interact with each other.

**Comment by marandaneto** [comment]
@stephane-archer happy that it is fixed.
this is how flutter packages work, https://docs.flutter.dev/packages-and-plugins/developing-packages

**Comment by stephane-archer** [comment]
@marandaneto can you force a pod update when someone updates their flutter package?
