### ISSUE TITLE
Access sessionId

### ISSUE THREAD

**Issue by colin-persona** [PostHog/posthog-ios#164]
### Problem Statement

I want to get and use sessionId for my own purposes (correlating your sessions with my server data). But, it's private. Could you make an accessor, or public?

`private var sessionId: String?`

### Solution Brainstorm

Make an accessor function.

**Comment by marandaneto** [comment]
@colin-persona that is fine, would you like to open a PR and make a read-only getter?

**Comment by colin-persona** [comment]
Yes. Yes I would, thanks! Here it is: https://github.com/PostHog/posthog-ios/pull/165

**Comment by colin-persona** [comment]
I didn't add to change log or bump version... figured you should do that?

**Comment by marandaneto** [comment]
done by https://github.com/PostHog/posthog-ios/pull/170
