### ISSUE TITLE
isFeatureEnabled returns false for enabled flag

### ISSUE THREAD

**Issue by Ehab-24** [PostHog/posthog-ios#169]
### Version

3.7.2

### Steps to Reproduce

1. Create a new feature flag in posthog dashboard
2. DO NOT assign a value to the flag
3. Enable and save the flag 
4. In you iOS app 

### Expected Result

`PostHogSDK.shared.isFeatureEnabled(flag)` should return true

### Actual Result

`PostHogSDK.shared.isFeatureEnabled(flag)` returns false even though the flag is shown as **enabled** in dashboard.

I used *lldb* and the issue is with this piece of code in `PostHog/PostHogFeatureFlags.swift:isFeatureEnabled`
```
        if value != nil {
            let boolValue = value as? Bool
            if boolValue != nil {
                return boolValue!
            } else {
                return true
            }
        } else {
  // omitted
```

The variable `boolValue` is initialized as `false` while typecasting if `value` is 0.

**Comment by marandaneto** [comment]
Hello @Ehab-24 
How are you creating your flag on the server?  can you share a screenshot or your org link|name so I can take a look?
I just tried to create a boolean flag with enabled and disabled and both results were correct.

![Screenshot 2024-08-26 at 10 42 30](https://github.com/user-attachments/assets/c922fda3-a682-4039-9274-17bd4b719032)

Could it be that you are calling `PostHogSDK.shared.isFeatureEnabled` before the server responds with all the flags?
If that's the case, you can do this https://posthog.com/docs/libraries/ios#ensuring-flags-are-loaded-before-usage

**Comment by marandaneto** [comment]
@Ehab-24 any update here?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
