### ISSUE TITLE
Add `$is_identified`

### ISSUE THREAD

**Issue by marandaneto** [PostHog/posthog-ios#172]
### Description

Relates to https://github.com/PostHog/posthog-android/issues/136

### Description

https://github.com/PostHog/posthog/pull/22216

`$is_identified` is the property to filter identified users or not (anonymous).

https://github.com/PostHog/posthog-js/blob/7022ab69505959fb065d41870d2bceeb69145916/src/posthog-core.ts#L912
JS SDK uses the `$user_state` super property to track if the user has identified already or not with the values `identified` or `anonymous` (this super property is in deny list so not set in the event)

Add to:
- [x] [Android](https://github.com/PostHog/posthog-android/pull/167)
- [ ] iOS
- [ ] RN

**Comment by marandaneto** [comment]
@beradeep would you like to take this one too?

**Comment by beradeep** [comment]
I would've loved to, but I don't a have mac right now :(
