### ISSUE TITLE
I/O on main thread leading to UI responsiveness issues

### ISSUE THREAD

**Issue by dingwilson** [PostHog/posthog-ios#176]
### Version

3.7.2

### Steps to Reproduce

Integrate PostHog into project and build

<img width="1381" alt="Screenshot 2024-08-30 at 8 50 48 AM" src="https://github.com/user-attachments/assets/6aa1754e-4723-4217-8322-8660f1eabed5">
<img width="1135" alt="Screenshot 2024-08-30 at 8 54 10 AM" src="https://github.com/user-attachments/assets/28ab51dc-705a-4fac-b66d-718e019ad9c4">

### Expected Result

PostHog integration should not cause any UI responsiveness issues

### Actual Result

Getting a lot of `File IO on Main Thread` sentry alerts

**Comment by marandaneto** [comment]
Hello @dingwilson thanks for reporting.
Indeed, the file will be read from the calling thread, and indeed it can be from the main thread although it's very fast and should not cause any responsiveness issues, do you experience any issues or just the alerts?
Can you enable the debug mode (`options.debug = true`) during SDK init and copy-paste the logs?
Thanks.

**Comment by dingwilson** [comment]
Hey @marandaneto - saw you addressed this already with the caching implementation. Thanks so much!

re: your questions - was definitely noticing some slowdown on UI side, as confirmed by the Sentry alerts I was receiving. I tried enabling debug mode but didn't really see any additional logs during SDK init. Is there something specific you are looking for?

**Comment by marandaneto** [comment]
@dingwilson I will release it later today, let's see if it improves otherwise we look at it again.

**Comment by dingwilson** [comment]
Thanks @marandaneto! Will test and report back once new version is cut

**Comment by marandaneto** [comment]
> Thanks @marandaneto! Will test and report back once new version is cut

released

**Comment by dingwilson** [comment]
Will run a test with a group of users in about 12hrs. Should have an update for you after that.

**Comment by dingwilson** [comment]
Issue seems to be resolved - thanks again for the fix + fast turnaround @marandaneto! 🎉
