### ISSUE TITLE
Can't install 3.8.3 with cocoapods.

### ISSUE THREAD

**Issue by iostrek** [PostHog/posthog-ios#182]
### Version

3.8.3

### Steps to Reproduce

Can't install 3.8.3 with cocoapods.

[!] CocoaPods could not find compatible versions for pod "PostHog":
  In Podfile:
    PostHog (= 3.8.3)

None of your spec sources contain a spec satisfying the dependency: `PostHog (= 3.8.3)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

### Expected Result

Can install 3.8.3 with cocoapods.

### Actual Result

Can't install 3.8.3 with cocoapods.

**Comment by marandaneto** [comment]
https://cocoapods.org/pods/PostHog is returning `Internal Server Error`, I think its a Cocoapods error.

The release failed indeed:

> [!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

**Comment by marandaneto** [comment]
https://cocoapods.org/pods/PostHog should be there, thanks
