### ISSUE TITLE
Xcode build error: Cannot find URLSession in scope

### ISSUE THREAD

**Issue by yood** [PostHog/posthog-ios#195]
### Version

3.12.0

### Steps to Reproduce

1. Add PostHog to Xcode 16 RC's Project's Package Dependencies, then add library to an iOS app target.
2. Add PostHog code to an iOS 18 app target.
3. Build iOS app target.

### Expected Result

Build succeeds

### Actual Result

Build fails due to error Cannot find type 'URLSession' in scope.

![CleanShot 2024-09-12 at 11 42 22@2x](https://github.com/user-attachments/assets/7742506f-1828-457d-acc0-8c1ae396c577)

Fix: add an 'import Foundation' to this PostHog/Replay/URLSessionExtension.swift. Confirmed using local package.

![CleanShot 2024-09-12 at 11 42 49@2x](https://github.com/user-attachments/assets/a0c96ee2-2a71-4c3e-b4a7-db1c2631a2c5)

**Comment by marandaneto** [comment]
fixed by https://github.com/PostHog/posthog-ios/pull/194 thanks
