### ISSUE TITLE
Get default person_profiles value from /decide endpoint

### ISSUE THREAD

**Issue by ioannisj** [PostHog/posthog-ios#219]
### Description

Ee now have a way in /decide to say who should be able to use anonymous events as the default config mode: https://github.com/PostHog/posthog/pull/25662

[ ] iOS
[ ] Android
[ ] React Native
[ ] Flutter

**Comment by marandaneto** [comment]
@ioannisj if this is a temporary solution for the rollout, maybe we should not do it unless this is gonna be used for remote config where people can change this setting via project configuration.
Can you confirm the intent of that?
