### ISSUE TITLE
Incompatible with WatchOS

### ISSUE THREAD

**Issue by Empty2k12** [PostHog/posthog-ios#23]
Due to usage of `PHGReachability` / `SystemConfiguration.h` this library is incompatible with WatchOS. Other analytics collection libraries like Segment are compatible.

**Comment by yakkomajuri** [comment]
Hey @Empty2k12! WatchOS is not currently a priority of ours, but we will happily take a PR with changes if you're willing!

**Comment by marandaneto** [comment]
Similar to https://github.com/PostHog/posthog-ios/issues/24 and https://github.com/PostHog/posthog-ios/issues/51 since checking at compile time would help
