### ISSUE TITLE
Wireframe Session Recording appears mangled

### ISSUE THREAD

**Issue by jadar** [PostHog/posthog-ios#231]
### Version

3.13.3

### Steps to Reproduce

1. Added PostHog to my project
2. Enabled session recording with the default method (wireframe) and disabled masking Images.
3. Started app and Recorded some sessions 
4. Went to PostHog to view them and they're mangled.

The app is a UIKit-based app, so there shouldn't be any issues with wireframe. Maybe one of my libraries is causing the issue if it does something weird to the view hierarchy?

### Expected Result

A nice wireframe layout of my app's UI

### Actual Result

<img width="275" alt="Screenshot 2024-11-05 at 9 48 22 AM" src="https://github.com/user-attachments/assets/336e1377-39e9-43ba-9816-f455e012a0fe">

**Comment by jadar** [comment]
@ioannisj Yes! UIStoryboard with autolayout.

**Comment by marandaneto** [comment]
@jadar a workaround for now would be to use the `screenshot` mode which does not have such issues.

**Comment by jadar** [comment]
@marandaneto Yep, that's what we're doing. :) We do that already on our SwiftUI apps too.
