### ISSUE TITLE
Support for macOS

### ISSUE THREAD

**Issue by txbrown** [PostHog/posthog-ios#24]
Can't install on a macOS target in a multi-paltform app (iOS+macOS).

**Comment by jeff-h** [comment]
Same issue for me — this won't compile for a Mac-only app. There are imports for UIKit in six classes which precludes compiling this for macOS.

`#import <UIKit/UIKit.h>`

**Comment by jeff-h** [comment]
I noticed in the [PostHog docs](https://posthog.com/docs/api/post-only-endpoints) that "you can use any of [our libraries](https://posthog.com/docs/integrate/overview) or any Mixpanel library". So I went with [the Mixpanel SPM package](https://github.com/mixpanel/mixpanel-swift) and it seems to be sending events through just fine from my Mac app to PostHog :)

**Comment by mcichecki** [comment]
@jeff-h how did you instantiate Mixpanel to use with PostHog? I tried to use a following code but couldn't get events in the PostHog.

```swift
Mixpanel.initialize(
    token: "...", // API KEY
    trackAutomaticEvents: false,
    serverURL: "https://app.posthog.com"
)
```

**Comment by marandaneto** [comment]
Similar to https://github.com/PostHog/posthog-ios/issues/51

**Comment by wasauce** [comment]
@marandaneto - will the new iOS sdk bring support to macOS? And or do you have a rough timeframe for when that could happen? I also see fromthe poster above -- that they used the Mixpanel SPM package -- does that method still work?

**Comment by marandaneto** [comment]
@wasauce the v3 SDK has compiler flags so it should just work on macOS, but a few features that depend on `UIKit` etc won't work but that's fine if you don't need them.
The first v3 alpha is out today.
Not sure if Mixpanel SDK is still compatible, that comment was 1y+ ago and the docs have been updated.

**Comment by marandaneto** [comment]
Similar to https://github.com/PostHog/posthog-ios/issues/24
Some features don't work because they depend on `UIKit` or something available only for iOS targets, but the SDK should do the basic stuff as sending events, etc.
https://github.com/PostHog/posthog-ios/releases/tag/3.0.0-alpha.2
