### ISSUE TITLE
Remove references to AdSupport framework?

### ISSUE THREAD

**Issue by sjmadsen** [PostHog/posthog-ios#4]
With Apple further restricting apps that track users in iOS 14, I'd like to see a version of this framework that removed any references to AdSupport or the IDFA (identifier for advertisers). The "upstream" repo that this one is based on has done this for their current 4.x release (see [this pull request](https://github.com/segmentio/analytics-ios/pull/892)), allowing apps that want to collect the IDFA to provide it, rather than having the framework itself make those calls into AdSupport.

How do PostHog iOS users feel about such a change? I'm happy to make the changes and create a PR if there is interest.

**Comment by jamesefhawkins** [comment]
Hey @sjmadsen , sorry for the slow response here.

I think this makes total sense as a PR if it's something you'd use and then wouldn't mind sharing. I imagine functionality-wise we should have:

* enabling apps that do not want ad tracking to pass App Store guidelines in certain categories while still allowing apps that do ad tracking to continue to function.
* to put a paragraph just to explain how to do the above [in here](https://posthog.com/docs/integrations/ios-integration)

**Comment by sjmadsen** [comment]
I'll get a PR together in the next few days.

**Comment by mariusandra** [comment]
This PR is now merged and version 1.1.0 of the library is out! Thanks again @sjmadsen !
