### ISSUE TITLE
Support for auto capture selected controller of UITabbarController

### ISSUE THREAD

**Issue by viktoricaloniapoplar** [PostHog/posthog-ios#46]
It seems that capturing screen of selected controller in UITabbarController is not triggering. Do i have to capture them manually?

**Comment by viktoricaloniapoplar** [comment]
nvm, as i have checked it is trigger.

**Comment by viktoricaloniapoplar** [comment]
As i have checked it will just capture screen name as UITabbarController not the selected viewcontroller of tabbarcontroller

**Comment by marandaneto** [comment]
@viktoricaloniapoplar can you provide a [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example)?
The Swizzling algo probably only detects the controllers but not tabs.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
