### ISSUE TITLE
_cachedStaticContext > Attempted to dereference garbage pointer

### ISSUE THREAD

**Issue by Max-Job** [PostHog/posthog-ios#50]
We use PostHog (1.4.4) and we get a fatal error:
> _cachedStaticContext > Attempted to dereference garbage pointer

<img width="591" alt="Screenshot 2023-05-05 at 17 51 28" src="https://user-images.githubusercontent.com/58559377/236507100-e67c1048-ae36-4f27-9d91-cfaa20c0479c.png">

could you help me to figure out what's wrong?

**Comment by marandaneto** [comment]
@Max-Job does that happen on the latest versions? eg https://github.com/PostHog/posthog-ios/releases/tag/2.0.5

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
