### ISSUE TITLE
IDFA AppStore submission issue (new)

### ISSUE THREAD

**Issue by artshin** [PostHog/posthog-ios#6]
Hey there,

Just wanted to share some AppStore results of ours with IDFA. Our app is catered towards kids and IDFA tracking is not allowed according to the security guidelines. We used a recent version `1.1.0` of `posthog-ios` in an AppStore submission. The app was rejected because of this [class](https://github.com/PostHog/posthog-ios/blob/7fb57d38fcc075057b3ae7d2d64d144e3b4b10e3/PostHog/Classes/Internal/PHGPostHogIntegration.m#L25) being used in code even as a static string constant. Since this string is used to dynamically initialize an instance of `ASIdentifierManager` class, it triggers a rejection from Apple. 

This happens even though `AdSupport` framework is not directly referenced or imported. 100% sure we didn't have `AdSupport.framework` file in the binary sent to Apple. Reviewed it with https://github.com/MobSF/Mobile-Security-Framework-MobSF

We ended up applying a patch to remove the constant and set the default value for ad tracking to false. After this, a new version of the app was approved.

Hope this helps! Cheers!

**Comment by mariusandra** [comment]
Hi @artshin , thank you for this explanation! I completely removed all references to the ad support framework with PRs #7 and #8 and published version `1.2.1`. Feel free to check it out and report back if it solves the problem for you. Happy to hear that you found a workaround though!
