### ISSUE TITLE
Crash on notification payload send

### ISSUE THREAD

**Issue by bddq** [PostHog/posthog-ios#61]
Hi,

I got an exception while using `PHGPostHog.shared()?.receivedRemoteNotification(userInfo)`.

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PHGPostHogIntegration receivedRemoteNotification:]: unrecognized selector sent to instance'
terminating with uncaught exception of type NSException
```

It seems that `receivedRemoteNotification` is not yet implemented.
I'm using PostHog SDK 2.0.3 through SPM.

Am I doing something wrong?

Thanks for your help.
Benoit

**Comment by marandaneto** [comment]
Fixed already https://github.com/PostHog/posthog-ios/releases/tag/2.0.4
Thanks!
