### ISSUE TITLE
Carthage installation not working

### ISSUE THREAD

**Issue by rickharrison** [PostHog/posthog-ios#64]
When installing posthog via carthage I am getting the following build error:

```
note: Building targets in dependency order
/Carthage/Checkouts/posthog-ios/Pods/Target Support Files/Pods-PostHog/Pods-PostHog.release.xcconfig:1:1: error: unable to open configuration settings file
warning: no rule to process file '/Users/rickharrison/Development/narwhal2/Carthage/Checkouts/posthog-ios/CHANGELOG.md' of type 'net.daringfireball.markdown' for architecture 'arm64' (in target 'PostHog' from project 'PostHog')
** ARCHIVE FAILED **
```

Xcode version: 14.3.1
macOS: 13.4.1

Any ideas on how to install this using carthage?

**Comment by marandaneto** [comment]
@rickharrison Thanks for the info.

If you do:

```
carthage update
cd Carthage/Checkouts/posthog-ios;pod install
carthage update
```

Does it work?

**Comment by rickharrison** [comment]
Thanks that appears to have worked:

```
carthage build posthog-ios --platform iOS --use-xcframeworks --no-use-binaries
*** xcodebuild output can be found in /var/folders/m9/2p5ztxyj6934tqgcrntmjz1w0000gn/T/carthage-xcodebuild.5tK8Pl.log
*** Building scheme "PostHog" in PostHog.xcworkspace
```

You might want to add that to this page: https://app.posthog.com/ingestion/mobile/ios

I can't be the only one who ran into this issue right?

**Comment by marandaneto** [comment]
@rickharrison thanks for the confirmation.

I've added a note to our [docs](https://github.com/PostHog/posthog.com/pull/6677).

The [page](https://app.posthog.com/ingestion/mobile/ios) you mentioned is being worked on [here](https://github.com/PostHog/posthog/blob/master/frontend/src/scenes/ingestion/frameworks/iOSInstructions.tsx) and [here](https://github.com/PostHog/posthog/blob/master/frontend/src/scenes/onboarding/sdks/product-analytics/ios.tsx) so I'll wait that to be finished before adding the note there.

Thanks.

**Comment by rickharrison** [comment]
@marandaneto It seems Carthage has been removed from the docs and all pages. Do you know why?

**Comment by marandaneto** [comment]
@rickharrison It is not very popular compared to SPM and Cocoapods, since we've rewritten the whole SDK, we did not implement it initially unless we saw the need for it.
Can you use either one of them or is Carthage a must? if so, please open a feature request, I don't recall anyone else needing it.

**Comment by rickharrison** [comment]
Are you able to use SPM with an objective-c project? We don't use cocoa pods because of how heavy it is, and we don't want to swap over to cocoa pods for a single dependency.

**Comment by marandaneto** [comment]
@rickharrison the new SDK (v3+) is swift only, so yes you can use SPM.
