### ISSUE TITLE
`handleActionWithIdentifier` throws if app is open from a notification - cold start

### ISSUE THREAD

**Issue by marandaneto** [PostHog/posthog-ios#70]
iOS unrecognized selector sent to instance

**Comment by cameronehrlich** [comment]
https://github.com/PostHog/posthog-ios/assets/1508740/fea86c8c-7e55-4b6a-a3f8-87c2acc3f855

<img width="1265" alt="Screenshot 2023-10-02 at 10 27 17 AM" src="https://github.com/PostHog/posthog-ios/assets/1508740/51755a3f-683a-489a-ae8b-443066074d47">

**Comment by marandaneto** [comment]
I can reproduce this locally as well, thanks for the video @cameronehrlich.
The app does not need to be in the background nor be opened via a notification, just calling:

```
    NSMutableDictionary *payload = [[NSMutableDictionary alloc] init];
    [[PHGPostHog sharedPostHog] handleActionWithIdentifier:(@"identifier")
                                     forRemoteNotification:(payload)];
```

The reason is that the `PHGPostHogIntegration` method does not have the `handleActionWithIdentifier` signature and this method is called dynamically [here](https://github.com/PostHog/posthog-ios/blob/d3eeb3b60bd54b5cb87299c40378118e642a4474/PostHog/Classes/PHGPayloadManager.m#L237) then [here](https://github.com/PostHog/posthog-ios/blob/d3eeb3b60bd54b5cb87299c40378118e642a4474/PostHog/Classes/PHGPayloadManager.m#L330).

This probably happens with 3 methods actually:

```
- (void)receivedRemoteNotification:(NSDictionary *)userInfo;
- (void)failedToRegisterForRemoteNotificationsWithError:(NSError *)error;
- (void)handleActionWithIdentifier:(NSString *)identifier forRemoteNotification:(NSDictionary *)userInfo;
```

If you call any of them, don't, an easy fix is to just add those methods (empty body) to `PHGPayloadManager` but I need to figure out what's supposed to be the implementation first, if any.

**Comment by marandaneto** [comment]
@benjackwhite do you have any context about that? what should those methods do?
