### ISSUE TITLE
`$session_id` support

### ISSUE THREAD

**Issue by marandaneto** [PostHog/posthog-ios#97]
### Description

Android already supports the `$session_id`
iOS not yet, this will be done with iOS session recording

Relates to https://github.com/PostHog/posthog-ios/pull/32 but this PR is table since the SDK was rewritten.

**Comment by mfclarke-cnx** [comment]
Hi @marandaneto, do you have an idea of when this will be shipped? We're very keen to make the switch, but the lack of session support is a total deal breaker for us.

**Comment by marandaneto** [comment]
Hi, yes, this is planned for the next week.
